# Generated by Django 5.2.13 on 2026-05-04 17:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInventoryItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('specs', models.CharField(max_length=512)),
                ('capacity', models.CharField(blank=True, max_length=128)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('deployed', 'Deployed'), ('out_of_stock', 'Out of stock'), ('na', 'N/A'), ('faulty', 'Faulty')], default='in_stock', max_length=32)),
                ('deployed_to', models.CharField(blank=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inventory item',
                'verbose_name_plural': 'historical inventory items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.CharField(max_length=512)),
                ('capacity', models.CharField(blank=True, max_length=128)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('deployed', 'Deployed'), ('out_of_stock', 'Out of stock'), ('na', 'N/A'), ('faulty', 'Faulty')], default='in_stock', max_length=32)),
                ('deployed_to', models.CharField(blank=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.category')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('deployed', 'Deployed'), ('returned', 'Returned'), ('removed', 'Removed'), ('faulty', 'Faulty'), ('qty_changed', 'Quantity changed'), ('remark_updated', 'Remark updated')], max_length=32)),
                ('quantity_before', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField(default=0)),
                ('deployed_to', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.inventoryitem')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
