# Generated by Django 5.2.14 on 2026-05-26 07:35

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('category', 'key'), name='uniq_attribute_choice_category_key')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInventoryItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('item_type', models.CharField(blank=True, max_length=128, null=True)),
                ('capacity_value', models.FloatField(blank=True, null=True)),
                ('capacity_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('interface', models.CharField(blank=True, max_length=64, null=True)),
                ('ports_1g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_10g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_25g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_40g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_100g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_other', models.CharField(blank=True, max_length=128, null=True)),
                ('cable_length_m', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='in_stock', max_length=32)),
                ('remark', models.TextField(blank=True)),
                ('activity_note', models.TextField(blank=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inventory item',
                'verbose_name_plural': 'historical inventory items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('item_type', models.CharField(blank=True, max_length=128, null=True)),
                ('capacity_value', models.FloatField(blank=True, null=True)),
                ('capacity_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('interface', models.CharField(blank=True, max_length=64, null=True)),
                ('ports_1g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_10g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_25g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_40g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_100g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_other', models.CharField(blank=True, max_length=128, null=True)),
                ('cable_length_m', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='in_stock', max_length=32)),
                ('remark', models.TextField(blank=True)),
                ('activity_note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.category')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('deployed', 'Deployed'), ('returned', 'Returned'), ('removed', 'Removed'), ('faulty', 'Faulty'), ('qty_changed', 'Quantity changed'), ('remark_updated', 'Remark updated'), ('status_changed', 'Status changed')], max_length=32)),
                ('quantity_before', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField(default=0)),
                ('deployed_to', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.inventoryitem')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', 'status'], name='core_invent_categor_b26714_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['updated_at'], name='core_invent_updated_53b285_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['name'], name='core_invent_name_0036f0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['timestamp'], name='core_invent_timesta_a597bd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['action'], name='core_invent_action_f40462_idx'),
        ),
    ]
