# Generated by Django 5.2.13 on 2026-05-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_hierarchical_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='custom_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='custom_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
