# Generated by Django 5.2.13 on 2026-05-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_custom_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventoryitem',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='historicalinventoryitem',
            name='deployed_to',
        ),
        migrations.RemoveField(
            model_name='historicalinventoryitem',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='deployed_to',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='specs',
        ),
    ]
