# Generated by GPT-5.2 on 2026-05-05

from django.db import migrations


def seed_misc_and_switch(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    InventoryItem = apps.get_model("core", "InventoryItem")

    def upsert_category(*, parent, name, description=""):
        obj, created = Category.objects.get_or_create(
            parent=parent,
            name=name,
            defaults={"description": description, "custom_fields": []},
        )
        if not created:
            dirty = False
            if obj.parent_id != (parent.id if parent else None):
                obj.parent = parent
                dirty = True
            if description is not None and (obj.description or "") != description:
                obj.description = description
                dirty = True
            if dirty:
                obj.save()
        return obj

    other = upsert_category(parent=None, name="Other", description="")
    misc = upsert_category(parent=other, name="Miscellaneous", description="Handy spares, tools, and misc parts")

    network = upsert_category(parent=None, name="Network Devices", description="")
    switch = upsert_category(parent=network, name="Switch", description="Network switches and related parts")

    schema = [
        {"name": "specs", "label": "Specs", "type": "string", "required": True, "choices": [], "unit": ""},
        {"name": "capacity", "label": "Capacity", "type": "string", "required": False, "choices": [], "unit": ""},
    ]
    for cat in (misc, switch):
        cat.custom_fields = schema
        cat.save(update_fields=["custom_fields"])

    misc_rows = [
        {"specs": "Dell R740 Backplane", "capacity": "24 Bay", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Dell Raid Controller", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "HP DL 380 G9 Backplane LFF", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "HP P440 AR Raid Controller", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Dell Heat Sink - Dell R740", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Console cable for SW/Router", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Console cable for Blade Server", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Small Tool kit (small screw driver set)", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Keyboard (only used when taking console)", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Monitor (only used when taking console)", "capacity": "", "quantity": 1, "status": "in_stock", "remark": ""},
        {"specs": "Comscope Ethernet Cable", "capacity": "", "quantity": 2, "status": "in_stock", "remark": ""},
        {"specs": "Reverse Power Cable 10Amp-C13/C14", "capacity": "", "quantity": 9, "status": "in_stock", "remark": ""},
    ]

    switch_rows = [
        {"specs": "EX3400 (Juniper-SW)", "capacity": "10G Port", "quantity": 4, "status": "in_stock", "remark": ""},
        {"specs": "EX3400 (Juniper-SW)", "capacity": "1G Port", "quantity": 24, "status": "in_stock", "remark": ""},
        {"specs": "EX3400 (Juniper-SW)", "capacity": "Port", "quantity": 2, "status": "in_stock", "remark": ""},
        {"specs": "S5736 (Huawei-SW)", "capacity": "1G Port", "quantity": 48, "status": "in_stock", "remark": ""},
        {"specs": "S5736 (Huawei-SW)", "capacity": "10G Port", "quantity": 4, "status": "in_stock", "remark": ""},
        {"specs": "Cisco Nexus 3000", "capacity": "", "quantity": 2, "status": "in_stock", "remark": ""},
    ]

    def upsert_item(category, row):
        custom_values = {"specs": row["specs"], "capacity": row.get("capacity", "") or ""}
        qty = int(row.get("quantity") or 0)
        status_val = row.get("status") or "in_stock"
        remark = row.get("remark") or ""

        obj, created = InventoryItem.objects.get_or_create(
            category=category,
            custom_values=custom_values,
            defaults={"quantity": qty, "status": status_val, "remark": remark},
        )
        if not created:
            dirty = False
            if obj.quantity != qty:
                obj.quantity = qty
                dirty = True
            if obj.status != status_val:
                obj.status = status_val
                dirty = True
            if (obj.remark or "") != remark:
                obj.remark = remark
                dirty = True
            if dirty:
                if obj.quantity == 0:
                    obj.status = "out_of_stock"
                obj.save()

    for row in misc_rows:
        upsert_item(misc, row)
    for row in switch_rows:
        upsert_item(switch, row)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_historicalinventoryitem_capacity_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_misc_and_switch, migrations.RunPython.noop),
    ]

