# Generated by GPT-5.2 on 2026-05-05

from django.db import migrations, models


RESERVED = {"specs", "capacity"}


def forwards(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    InventoryItem = apps.get_model("core", "InventoryItem")

    # Backfill item columns from existing custom_values when present.
    qs = InventoryItem.objects.all().only("id", "custom_values", "quantity")
    for item in qs.iterator():
        cv = item.custom_values or {}
        raw_specs = cv.get("specs", None)
        raw_capacity = cv.get("capacity", None)
        specs = (str(raw_specs).strip() if raw_specs is not None else "") or f"Item #{item.id}"
        capacity = str(raw_capacity).strip() if raw_capacity is not None else ""
        InventoryItem.objects.filter(pk=item.pk).update(specs=specs, capacity=capacity)

        # Remove migrated keys from custom_values to avoid validation conflicts later.
        if any(k in cv for k in RESERVED):
            next_cv = dict(cv)
            for k in list(RESERVED):
                next_cv.pop(k, None)
            InventoryItem.objects.filter(pk=item.pk).update(custom_values=next_cv)

    # Remove reserved fields from category custom schema if they exist (Option 1: model fields win).
    for cat in Category.objects.all().only("id", "custom_fields").iterator():
        fields = cat.custom_fields or []
        if not isinstance(fields, list):
            continue
        next_fields = [f for f in fields if isinstance(f, dict) and str(f.get("name") or "").strip() not in RESERVED]
        if next_fields != fields:
            Category.objects.filter(pk=cat.pk).update(custom_fields=next_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_seed_misc_switch_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="specs",
            field=models.CharField(max_length=512, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="capacity",
            field=models.CharField(max_length=128, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="specs",
            field=models.CharField(max_length=512, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="capacity",
            field=models.CharField(max_length=128, blank=True, default=""),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="inventoryitem",
            name="specs",
            field=models.CharField(max_length=512),
        ),
    ]

