# Generated by Django 5.2.13 on 2026-05-05 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_specs_capacity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='specs',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
