# Generated by Django 5.2.14 on 2026-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_historicalinventoryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableitem',
            name='cable_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpuitem',
            name='architecture',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='status',
            field=models.CharField(default='in_stock', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo or illustration of the item', null=True, upload_to='inventory/'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(default='in_stock', max_length=32),
        ),
        migrations.AlterField(
            model_name='ramitem',
            name='form_factor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ramitem',
            name='memory_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sfpitem',
            name='sfp_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='brand',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='drive_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='interface',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='switchitem',
            name='brand',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('category', 'key'), name='uniq_attribute_choice_category_key')],
            },
        ),
    ]
